lang:
  visualizerEnabled: "&aYour visualizer has been enabled."
  visualizerDisabled: "&cYour visualizer has been disabled."
  playersOnly: "&cOnly a player can toggle his visualizer."
  maxSelection: "&6The visualizer only works with selections up to a size of %blocks% blocks"
  configReloaded: "&aConfiguration for visualizer was reloaded from the disk."
  noPermission: "&cYou don't have the permission to use this command."
updateChecker: true
particleDistance: 32
maxSize: 10000
checkForAxe: false
particleEffect: REDSTONE
particleData: "255,0,0"
horizontalLinesForCuboid: true
horizontalLinesForPolygon: true
horizontalLinesForCylinder: true
horizontalLinesForEllipsoid: true
topAndBottomForCuboid: true
topAndBottomForCylinder: true
gapBetweenPoints: 0.5
verticalGap: 1
updateSelectionInterval: 20
updateParticlesInterval: 5
particleFadeDelay: 0
players: